class Autogenerated {
  String reason;
  Result result;

  Autogenerated({this.reason, this.result});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    reason = json['reason'];
    result =
    json['result'] != null ? new Result.fromJson(json['result']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['reason'] = this.reason;
    if (this.result != null) {
      data['result'] = this.result.toJson();
    }
    return data;
  }
}

class Result {
  String stat;

  Result({this.stat});

  Result.fromJson(Map<String, dynamic> json) {
    stat = json['stat'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['stat'] = this.stat;
    return data;
  }
}